#!/usr/bin/env python3
"""Generate RSS feed for private podcast."""

import os
import sys
from pathlib import Path
from datetime import datetime
import mimetypes
from mutagen.mp3 import MP3

PODCAST_DIR = Path.home() / "code" / "podcast-feed"
EPISODES_DIR = PODCAST_DIR / "episodes"
FEED_FILE = PODCAST_DIR / "feed.xml"

def get_mp3_duration(filepath):
    """Get duration of MP3 in seconds."""
    try:
        audio = MP3(filepath)
        return int(audio.info.length)
    except:
        return 0

def format_duration(seconds):
    """Format seconds as HH:MM:SS."""
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:02d}"

def generate_feed(base_url):
    """Generate RSS feed XML."""
    episodes = sorted(EPISODES_DIR.glob("*.mp3"), key=lambda p: p.stat().st_mtime, reverse=True)

    items = []
    for ep in episodes:
        stat = ep.stat()
        duration = get_mp3_duration(ep)
        pub_date = datetime.fromtimestamp(stat.st_mtime).strftime("%a, %d %b %Y %H:%M:%S +0000")
        title = ep.stem.replace("_", " ").replace("-", " ").title()

        items.append(f"""
    <item>
      <title>{title}</title>
      <enclosure url="{base_url}/episodes/{ep.name}" length="{stat.st_size}" type="audio/mpeg"/>
      <guid>{base_url}/episodes/{ep.name}</guid>
      <pubDate>{pub_date}</pubDate>
      <itunes:duration>{format_duration(duration)}</itunes:duration>
      <description>Generated by jsmith TTS</description>
    </item>""")

    feed = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Jsmith TTS</title>
    <description>Private podcast feed for text-to-speech audio</description>
    <link>{base_url}</link>
    <atom:link href="{base_url}/feed.xml" rel="self" type="application/rss+xml"/>
    <language>en-us</language>
    <itunes:author>Jsmith</itunes:author>
    <itunes:category text="Technology"/>
    <itunes:explicit>false</itunes:explicit>
    <itunes:image href="{base_url}/cover.png"/>
{"".join(items)}
  </channel>
</rss>"""

    FEED_FILE.write_text(feed)
    print(f"Generated feed with {len(episodes)} episodes at {FEED_FILE}")
    return FEED_FILE

if __name__ == "__main__":
    base_url = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8000"
    generate_feed(base_url)
